name: .NET

on:
  push:
    branches: [ main ]
    paths-ignore:
      - README.md
  pull_request:
    branches: [ main ]

env:
  AZURE_RG: techorama-lab2
  AZURE_SUBSCRIPTION: 8986d317-de76-4b66-88d3-8c637573841d
  AZURE_LOCATION: eastUS

jobs:
  Build-Job:
    runs-on: ubuntu-latest
    env:
      configuration: release

    steps:
    - name: Checkout Sources
      uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration ${{ env.configuration }}
    - name: Test
      run: dotnet test --no-build --verbosity normal --configuration ${{ env.configuration }}
    - name: Publish 
      run: dotnet publish --configuration ${{ env.configuration }} --output ${{ runner.temp }}/publish
    - name: Upload the Publish artefact
      uses: actions/upload-artifact@v3.0.0
      with:
        name: publish_artifact
        path: ${{ runnen.temp }}/publish
        retention-days: 30
    - name: Upload Template Artifact
      uses: actions/upload-artifact@3.0.0
      with:
        name: templates_artifact
        path: ./templates/*
        retention-days: 30
